#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-calculation"
kubernetesNamespace="ffc-demo"

(
  cd "${projectRoot}"

  helm upgrade \
    --install \
    --namespace ${kubernetesNamespace} \
     ${dockerPrefix}-service \
    ./helm/ffc-demo-calculation-service
)
