#!/bin/sh

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/../.." || return; pwd)"

# Set expected prefix for Docker resource names managed by this script
dockerPrefix="ffc-demo-calculation"

(
  cd "${projectRoot}"

  helm upgrade ${dockerPrefix}-service --install --namespace ${dockerPrefix}-service ./helm
)
