#!/bin/bash

docker network inspect mine-support &>/dev/null || docker network create mine-support

docker-compose -f docker-compose.yaml -f docker-compose.test.yaml down -v
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml build --no-cache mine-support-calculation-service
docker-compose -f docker-compose.yaml -f docker-compose.test.yaml up --force-recreate mine-support-calculation-service
